config/routes.rb
Rails.application.routes.draw do
  resources :playlist_items, only: [:create]
  resources :playlists, only: [:index, :show, :new, :create, :edit] do
    resources :playlist_items, only: [:create, :destroy]
    member do
      patch :update_title
      delete :remove_videos
    end
  end
  root 'home#index'
  get 'videos/:id', to: 'home#show', as: 'video'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_many :playlist_items, dependent: :destroy
end
  

app/models/playlist_item.rb
class PlaylistItem < ApplicationRecord
  belongs_to :playlist
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    video_service = VideoService.new

    # Preprocessing --> make sure page is inteter
    if params[:page].present?
      params[:page] = params[:page].to_i
    end

    # Handle Search
    if params[:query].present?
      @videos = video_service.get_videos_by_query(params[:query], page: params[:page] || 1)
      @meta = { 'total' => @videos.total_count, 'page' => params[:page] || 1 }
 
      if @videos.empty?
        flash[:notice] = "No videos found matching your search criteria"
      end
    # Handle regular browsing
    else
      @videos = video_service.list_videos(page: params[:page] || 1)
      @meta = { 'total' => @videos.total_count, 'page' => params[:page] || 1 }
 
      if @videos.empty?
        flash[:alert] = "Failed to fetch videos"
      end
    end

    # Postprocessing --> Make sure meta page is not nil (breaks view)
    @meta['page'] ||= 1
  end
  def show
      video_service = VideoService.new
      video_id = params[:id].to_i

      begin
        # Fetch the video details by its ID
        @video = video_service.get_video_by_id(video_id)

      rescue StandardError => e
        flash[:alert] = "An error occurred: #{e.message}"
        redirect_to root_path
      end
    end  
end

app/controllers/playlist_items_controller.rb
class PlaylistItemsController < ApplicationController
  # POST /playlist_items
  def create
    playlist_ids = params[:playlist_ids]
    video_id = params[:video_id]

    playlist_ids.each do |playlist_id|
      PlaylistItem.create(playlist_id: playlist_id, video_id: video_id)
    end

    redirect_to root_path, notice: "Video added to selected playlists."
  end

  # DELETE /playlist_items/:id
  def destroy
    playlist_item = PlaylistItem.find(params[:id])
    playlist_item.destroy

    redirect_back(fallback_location: root_path, notice: "Video removed from the playlist.")
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy update_title remove_videos ]

  def index
    @playlists = PlaylistService.new.list_playlists

    if params[:context] == 'add_to_playlist' && params[:video_id].present?
      @video_id = params[:video_id]
      render partial: 'playlists/add_to_playlist'
    else
      render partial: 'playlists/list_playlists'
    end
  end

  def show
    playlists_service = PlaylistService.new

    @videos = playlists_service.get_playlist_items(@playlist.id)
        
  end

  def update_title
    if PlaylistService.new.update_playlist(@playlist.id, playlist_params[:name])
      redirect_to @playlist, notice: 'Failed to update playlist'
    else
      redirect_to @playlist, alert: 'Failed  to update playlist'
    end
  end

  def remove_videos
    playlist_service = PlaylistService.new

    # Split the video_ids string into an array of strings, then map them to integers
    video_ids = params[:video_ids].first.split(',').map(&:to_i)

    # Use the updated method to remove multiple items at once
    playlist_service.remove_playlist_items(@playlist.id, video_ids)

    redirect_to @playlist, notice: 'Selected videos were removed from the playlist.'
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = PlaylistService.new.create_playlist(playlist_params[:name])

    respond_to do |format|
      if @playlist.persisted?
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    PlaylistService.new.delete_playlist(@playlist.id)
    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_playlist
      @playlist = PlaylistService.new.get_playlist_by_id(params[:id])
    end

    def playlist_params
      params.require(:playlist).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/playlist_items_helper.rb
module PlaylistItemsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Collab Code Challenge', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Videos', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link" data-bs-toggle="offcanvas" data-bs-target="#playlistsOffcanvas" onclick="loadPlaylists()">Playlists</a>
        </li>
      </ul>
      <form class="d-flex" role="search" action="<%= root_path %>" method="get">
        <input class="form-control me-2" type="search" name="query" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<script>
  function loadPlaylists() {
    fetch('/playlists')
      .then(response => response.text())
      .then(html => {
        document.getElementById('playlists-content').innerHTML = html;
      });
  }
</script>

app/views/home/index.html.erb
<% if @videos.any? %>
    <div class="container">
    <div class="row mt-5">
        <% @videos.each do |video| %>
            <div class="col-md-3 mb-4">
            <%= link_to video_path(video['id']), class: "text-decoration-none text-dark" do %>
                <div class="card border-0">
                    <img src="<%= video['thumbnail_url'] %>" class="card-img-top rounded" alt="<%= video['title'] %>">
                    <div class="card-body p-2">
                        <p class="mb-0"><strong><%= video['title'] %></strong></p>
                        <p class="card-text"><small class="text-muted">Views: <%= number_with_delimiter(video['views']) %></small></p>
                    </div>
                </div>
            <% end %>
            </div>
        <% end %>
        </div>
    </div>

    <!-- Pagination -->
    <div class="row">
        <div class="col-12">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                <% if @meta['page'] > 1 %>
                    <li class="page-item">
                    <%= link_to '&laquo;'.html_safe, root_path(page: @meta['page'] - 1), class: 'page-link' %>
                    </li>
                <% else %>
                    <li class="page-item disabled">
                    <span class="page-link">&laquo;</span>
                    </li>
                <% end %>

                <%# Displaying the numbered page links %>
                <% ((@meta['page'] - 2)..(@meta['page'] + 2)).each do |page| %>
                    <% if page > 0 && page <= (@meta['total'] / 10.0).ceil %>
                    <% if page == @meta['page'] %>
                        <li class="page-item active">
                        <span class="page-link"><%= page %></span>
                        </li>
                    <% else %>
                        <li class="page-item">
                        <%= link_to page, root_path(page: page), class: 'page-link' %>
                        </li>
                    <% end %>
                    <% end %>
                <% end %>

                <%# Next Page Link %>
                <% if @meta['page'] < (@meta['total'] / 10.0).ceil %>
                    <li class="page-item">
                    <%= link_to '&raquo;'.html_safe, root_path(page: @meta['page'] + 1), class: 'page-link' %>
                    </li>
                <% else %>
                    <li class="page-item disabled">
                    <span class="page-link">&raquo;</span>
                    </li>
                <% end %>
            </ul>
        </nav>
        </div>
    </div>
    </div>
<% else %>
<p>No videos available.</p>
<% end %>

app/views/home/show.html.erb
<div class="container mt-4">
  <!-- Video Thumbnail -->
  <div class="row">
    <div class="col-12">
      <!-- YouTube Video Embed with larger size -->
      <div class="embed-responsive embed-responsive-16by9" style="height: 500px;">
        <iframe class="embed-responsive-item w-100 h-100" src="https://www.youtube.com/embed/<%= @video['video_id'] %>" allowfullscreen></iframe>
      </div>
    </div>
  </div>

  <!-- Title and Video Stats -->
  <div class="row mt-3 align-items-center">
    <div class="col-6">
      <p class="h4"><%= @video['title'] %></p>
    </div>
    <div class="col-md-2">
      <p>Views: <%= number_with_delimiter(@video['views']) %></p>
    </div>
    <div class="col-md-2">
      <p>Likes: <%= number_with_delimiter(@video['likes']) %></p>
    </div>
    <div class="col-md-2">
      <p>Comments: <%= number_with_delimiter(@video['comments']) %></p>
    </div>
  </div>

  <!-- Save to Playlist Button -->
  <div class="row mt-3">
    <div class="col-12">
      <button class="btn btn-primary" data-bs-toggle="offcanvas" data-bs-target="#playlistsOffcanvas" onclick="loadPlaylistsForVideo(<%= @video['id'] %>)">
        Save to Playlist
      </button>
    </div>
  </div>

  <!-- Description with "View More" -->
  <div class="row mt-3">
    <div class="col-12">
      <div id="description-preview" class="mb-3">
        <%= truncate(@video['description'], length: 100) %>
        <a href="#" id="view-more">View More</a>
      </div>
      <div id="full-description" class="d-none">
        <%= @video['description'] %>
        <a href="#" id="view-less">View Less</a>
      </div>
    </div>
  </div>
</div>

<script>
  function loadPlaylistsForVideo(videoId) {
    fetch('/playlists?context=add_to_playlist&video_id=' + videoId)
      .then(response => response.text())
      .then(html => {
        document.getElementById('playlists-content').innerHTML = html;
      });
  }

  document.addEventListener('DOMContentLoaded', function() {
    const viewMore = document.getElementById('view-more');
    const viewLess = document.getElementById('view-less');
    const descriptionPreview = document.getElementById('description-preview');
    const fullDescription = document.getElementById('full-description');

    viewMore.addEventListener('click', function(e) {
      e.preventDefault();
      descriptionPreview.classList.add('d-none');
      fullDescription.classList.remove('d-none');
    });

    viewLess.addEventListener('click', function(e) {
      e.preventDefault();
      fullDescription.classList.add('d-none');
      descriptionPreview.classList.remove('d-none');
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollabCodeChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
</html>
  <body>
    <%= render 'home/navbar' %>
    <%= yield %>

    <!-- Offcanvas for Playlists -->
    <div class="offcanvas offcanvas-end" tabindex="-1" id="playlistsOffcanvas" aria-labelledby="playlistsOffcanvasLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="playlistsOffcanvasLabel">Playlists</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <div id="playlists-content">
          <!-- Content will be dynamically loaded based on the context -->
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <p>Author: André  Luiz Tiago Soares</p>
  </body>
</html>

app/views/playlists/_add_to_playlist.html.erb
<div id="playlists">
  <%= form_with url: playlist_items_path, method: :post, local: true do %>
    <input type="hidden" name="video_id" value="<%= @video_id %>">
    <% @playlists.each do |playlist| %>
      <div class="playlist-item form-check mb-3">
        <input class="form-check-input" type="checkbox" name="playlist_ids[]" value="<%= playlist.id %>" id="playlist_<%= playlist.id %>">
        <label class="form-check-label" for="playlist_<%= playlist.id %>">
          <%= playlist.name %>
        </label>
      </div>
    <% end %>
    <div class="d-grid">
      <button type="submit" class="btn btn-success">Save to Selected Playlists</button>
    </div>
  <% end %>
</div>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist) do |form| %>
  <% if playlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/_form_fields.html.erb
<!-- app/views/playlists/_form_fields.html.erb -->
<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>
</div>

app/views/playlists/_list_playlists.html.erb
<div id="playlists">
  <% @playlists.each do |playlist| %>
    <div class="playlist-item mb-3">
      <p>
        <%= link_to playlist.name, playlist_path(playlist) %>
      </p>
    </div>
  <% end %>
</div>
<%= link_to "New playlist", new_playlist_path, class: "btn btn-primary mt-3" %>

app/views/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">
  <p>
    <strong>Name:</strong>
    <%= playlist.name %>
  </p>

</div>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Show this playlist", @playlist %> |
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Playlists</h1>

<div id="playlists">
  <% @playlists.each do |playlist| %>
    <%= render playlist %>
    <p>
      <%= link_to "Show this playlist", playlist %>
    </p>
  <% end %>
</div>

<%= link_to "New playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h4 class="mb-0">Create a New Playlist</h4>
        </div>
        <div class="card-body">
          <!-- Render the form partial -->
          <%= form_with(model: @playlist, local: true) do |form| %>
            <%= render "form_fields", form: form %>
            <div class="card-footer text-right">
              <%= link_to "Back to home", root_path, class: "btn btn-secondary mr-2" %>
              <%= form.submit "Create Playlist", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/playlists/show.html.erb
<div class="container mt-4" id="playlist-show" data-context="normal">
  <!-- Editable Title -->
  <div class="row">
    <div class="col-12">
      <h1 id="playlist-title" contenteditable="false"><%= @playlist.name %></h1>
      <%= form_with model: @playlist, url: update_title_playlist_path(@playlist), method: :patch, id: 'edit-playlist-form', local: true do %>
        <input type="hidden" id="playlist-title-input" name="playlist[name]" value="<%= @playlist.name %>">
      <% end %>
    </div>
  </div>

  <!-- Action Buttons -->
  <div class="row mb-3">
    <div class="col-12">
      <button id="edit-button" class="btn btn-primary">Edit</button>
      <button id="remove-button" class="btn btn-danger">Remove Videos</button>
      <button id="confirm-button" class="btn btn-success d-none">Confirm Changes</button>
      <button id="cancel-button" class="btn btn-secondary d-none">Cancel</button>
    </div>
  </div>

  <!-- Videos List -->
  <div class="row">
    <% @videos.each do |video| %>
      <div class="col-md-3 mb-4">
        <div class="video-container">
          <%= check_box_tag 'video_ids[]', video['id'], false, class: 'video-checkbox d-none' %>
          <%= link_to video_path(video['id']), class: "text-decoration-none text-dark" do %>
            <div class="card border-0">
              <img src="<%= video['thumbnail_url'] %>" class="card-img-top" alt="<%= video['title'] %>">
              <div class="card-body p-2">
                <p class="mb-0"><strong><%= video['title'] %></strong></p>
                <p class="card-text"><small class="text-muted">Views: <%= number_with_delimiter(video['views']) %></small></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= form_with url: remove_videos_playlist_path(@playlist), method: :delete, id: 'remove-videos-form' do %>
  <% # This field will now hold the array of video IDs %>
  <input type="hidden" name="video_ids[]" id="selected-video-ids">
<% end %>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const contextElement = document.getElementById('playlist-show');
  const titleElement = document.getElementById('playlist-title');
  const titleInputElement = document.getElementById('playlist-title-input');
  const editButton = document.getElementById('edit-button');
  const removeButton = document.getElementById('remove-button');
  const confirmButton = document.getElementById('confirm-button');
  const cancelButton = document.getElementById('cancel-button');
  const videoCheckboxes = document.querySelectorAll('.video-checkbox');
  const removeForm = document.getElementById('remove-videos-form');
  const selectedVideoIdsInput = document.getElementById('selected-video-ids');

  function changeContext(context) {
    contextElement.setAttribute('data-context', context);

    switch (context) {
      case 'edit':
        titleElement.setAttribute('contenteditable', 'true');
        titleElement.focus();
        editButton.classList.add('d-none');
        removeButton.classList.add('d-none');
        confirmButton.classList.remove('d-none');
        cancelButton.classList.remove('d-none');
        break;
      case 'remove_from_playlist':
        videoCheckboxes.forEach(cb => cb.classList.remove('d-none'));
        editButton.classList.add('d-none');
        removeButton.classList.add('d-none');
        confirmButton.classList.remove('d-none');
        cancelButton.classList.remove('d-none');
        break;
      default: // 'normal'
        titleElement.setAttribute('contenteditable', 'false');
        videoCheckboxes.forEach(cb => {
          cb.classList.add('d-none');
          cb.checked = false; // Reset checkboxes when switching context
        });
        editButton.classList.remove('d-none');
        removeButton.classList.remove('d-none');
        confirmButton.classList.add('d-none');
        cancelButton.classList.add('d-none');
        break;
    }
  }

  editButton.addEventListener('click', function() {
    changeContext('edit');
  });

  removeButton.addEventListener('click', function() {
    changeContext('remove_from_playlist');
  });

  confirmButton.addEventListener('click', function() {
    if (contextElement.getAttribute('data-context') === 'edit') {
      titleInputElement.value = titleElement.innerText;
      document.getElementById('edit-playlist-form').submit();
    } else if (contextElement.getAttribute('data-context') === 'remove_from_playlist') {
      const selectedVideoIds = Array.from(videoCheckboxes)
      .filter(cb => cb.checked)
      .map(cb => cb.value);

      selectedVideoIdsInput.value = selectedVideoIds; // Assign the array directly
      removeForm.submit();
    }
  });

  cancelButton.addEventListener('click', function() {
    changeContext('normal');
  });

  document.addEventListener('keydown', function(event) {
    if (event.key === 'Escape') {
      changeContext('normal');
    } else if (event.key === 'Enter' && contextElement.getAttribute('data-context') === 'edit') {
      confirmButton.click();
    }
  });
});
</script>